#!/usr/bin/env bash
# LockedinOS First-Boot Setup Wizard
# Runs on the first user login to collect preferences
# Autostarted via ~/.config/autostart/lockedin-wizard.desktop
set -euo pipefail

CONFIG_DIR="$HOME/.config/lockedin"
WIZARD_DONE_FILE="$CONFIG_DIR/.wizard-done"

# Skip if already completed
if [ -f "$WIZARD_DONE_FILE" ]; then
  exit 0
fi

mkdir -p "$CONFIG_DIR"

# Use zenity for a simple GUI wizard
if ! command -v zenity &>/dev/null; then
  echo "zenity not found, skipping wizard"
  touch "$WIZARD_DONE_FILE"
  exit 0
fi

# Welcome dialog
zenity --info \
  --title="Welcome to LockedinOS" \
  --text="Welcome to LockedinOS!\n\nThis quick setup wizard will help you personalize your experience.\n\nDesigned for students, by students." \
  --width=400 --height=200 \
  2>/dev/null || true

# Collect name
NAME=$(zenity --entry \
  --title="LockedinOS Setup" \
  --text="What's your name?" \
  --entry-text="Student" \
  --width=350 \
  2>/dev/null) || NAME="Student"

# Collect school email (optional)
EMAIL=$(zenity --entry \
  --title="LockedinOS Setup" \
  --text="School email (optional, stored locally only):" \
  --width=350 \
  2>/dev/null) || EMAIL=""

# Focus mode preference
FOCUS_DEFAULT=$(zenity --list \
  --title="Focus Mode Preference" \
  --text="When should focus mode activate by default?" \
  --radiolist \
  --column="Select" --column="Option" \
  TRUE "Manual only (I'll toggle it myself)" \
  FALSE "Suggest during school hours (8am-3pm)" \
  FALSE "Always suggest when laptop opens" \
  --width=450 --height=300 \
  2>/dev/null) || FOCUS_DEFAULT="Manual only (I'll toggle it myself)"

# Save preferences
cat > "$CONFIG_DIR/preferences.conf" << EOF
# LockedinOS User Preferences
# Generated by first-boot wizard
STUDENT_NAME="${NAME}"
STUDENT_EMAIL="${EMAIL}"
FOCUS_PREFERENCE="${FOCUS_DEFAULT}"
SETUP_DATE="$(date -Iseconds)"
EOF

# Final confirmation
zenity --info \
  --title="Setup Complete" \
  --text="Welcome, ${NAME}!\n\nYour LockedinOS is ready.\n\nTip: Press the Tasks icon in the dock to start managing your tasks.\nUse Focus Mode to block distractions when studying." \
  --width=400 --height=200 \
  2>/dev/null || true

# Mark wizard as done
touch "$WIZARD_DONE_FILE"

echo "First-boot wizard completed for $NAME"
